version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - dependency-cache-{{ .Branch }}-
            - dependency-cache-
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - store_artifacts:
          path: ./coverage
      - save_cache:
          paths:
            - ./.next/cache
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
workflows:
    build-and-test:
      jobs:
        - build-and-test
